// <auto-generated />
using System;
using Bisuteria.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bisuteria.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("apellido1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellido2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<float>("descuento")
                        .HasColumnType("real");

                    b.Property<int?>("productoid")
                        .HasColumnType("int");

                    b.Property<float>("subtotal")
                        .HasColumnType("real");

                    b.Property<int?>("ventaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("productoid");

                    b.HasIndex("ventaid");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("material")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("categoriaid")
                        .HasColumnType("int");

                    b.Property<string>("codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("materialid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("peso")
                        .HasColumnType("real");

                    b.Property<float>("precio_compra")
                        .HasColumnType("real");

                    b.Property<float>("precio_venta")
                        .HasColumnType("real");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.Property<string>("talla")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("categoriaid");

                    b.HasIndex("materialid");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Venta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("clienteid")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ganancia")
                        .HasColumnType("real");

                    b.Property<string>("medio_pago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<float>("valor_total")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Item", b =>
                {
                    b.HasOne("Bisuteria.App.Dominio.Entidades.Producto", "producto")
                        .WithMany()
                        .HasForeignKey("productoid");

                    b.HasOne("Bisuteria.App.Dominio.Entidades.Venta", "venta")
                        .WithMany()
                        .HasForeignKey("ventaid");

                    b.Navigation("producto");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Producto", b =>
                {
                    b.HasOne("Bisuteria.App.Dominio.Entidades.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaid");

                    b.HasOne("Bisuteria.App.Dominio.Entidades.Material", "material")
                        .WithMany()
                        .HasForeignKey("materialid");

                    b.Navigation("categoria");

                    b.Navigation("material");
                });

            modelBuilder.Entity("Bisuteria.App.Dominio.Entidades.Venta", b =>
                {
                    b.HasOne("Bisuteria.App.Dominio.Entidades.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");

                    b.Navigation("cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
